---
# These tasks install http and the php modules.

- name: Install http and php etc
  apt: name={{ item }} state=present
  with_items:
   - apache2
   - libapache2-mod-php5
   - php5-mysql
   - git
   - python-semanage
   - python-selinux

- name: http service state
  service: name=apache2 state=started enabled=yes

#- name: Configure SELinux to allow httpd to connect to remote database
  #seboolean: name=httpd_can_network_connect_db state=true persistent=yes 
