---
# This playbook contains common plays that will be run on all nodes.

- name: refresh apt
  apt: update-cache=yes

- name: Install ntp 
  apt: name=ntp state=present
  tags: ntp

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntp state=started enabled=true
  tags: ntp
